# Generated by Django 5.1.4 on 2024-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_useraccount_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text="User's full name", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nid_number',
            field=models.CharField(help_text='National ID number', max_length=20, unique=True),
        ),
    ]
